name: Lean Action CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Lean Action
        uses: leanprover/lean-action@v1

      - name: Docgen
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: leanprover-community/docgen-action@v1
